#!/usr/bin/env python3
"""
Briefing Renderers - Output formatting for different channels

Supports:
- Markdown: For email, GitHub, or reading apps
- HTML: For rich email or web display
- Plain Text: For terminal or SMS
"""

from datetime import datetime
from typing import Protocol

from briefing.generator import BriefingResult, BriefingSection


class Renderer(Protocol):
    """Protocol for briefing renderers."""

    def render(self, result: BriefingResult) -> str:
        ...


class MarkdownRenderer:
    """Render briefing as Markdown."""

    def render(self, result: BriefingResult) -> str:
        lines = []

        # Header
        date_str = datetime.now().strftime('%A, %B %d, %Y')
        lines.append(f"# 📰 Morning Briefing - {date_str}")
        lines.append("")

        # Metadata summary
        meta = result.metadata
        lines.append(f"**{meta.total_stories} stories** from {meta.sources_used} sources")
        lines.append(f"• 🔴 {meta.must_read_count} must-read")
        lines.append(f"• 🟡 {meta.important_count} important")
        lines.append(f"• 🟢 {meta.contextual_count} contextual")
        lines.append(f"• ⏱️ ~{meta.reading_time_minutes} min read")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Sections
        for section in result.sections:
            lines.append(self._render_section(section))

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by High-Signal News*")

        return '\n'.join(lines)

    def _render_section(self, section: BriefingSection) -> str:
        lines = []
        lines.append(f"## {section.emoji} {section.name}")
        lines.append("")

        if not section.stories:
            lines.append("*No stories in this section.*")
            lines.append("")
            return '\n'.join(lines)

        for story in section.stories:
            tier = story.get('tier', 'contextual')
            urgency = story.get('urgency', 'normal')

            # Priority indicator
            tier_emoji = {'must_read': '🔴', 'important': '🟡', 'contextual': '🟢'}.get(tier, '⚪')
            urgency_marker = ' **BREAKING**' if urgency == 'breaking' else ' **URGENT**' if urgency == 'urgent' else ''

            # Title with link if available
            title = story.get('title', 'Untitled')
            url = story.get('url')
            if url:
                lines.append(f"### {tier_emoji} [{title}]({url}){urgency_marker}")
            else:
                lines.append(f"### {tier_emoji} {title}{urgency_marker}")

            # Summary
            summary = story.get('summary', '')
            if summary:
                lines.append(summary)
                lines.append("")

            # Metadata line
            meta_parts = []

            sources = story.get('sources', [])
            if sources:
                source_str = ', '.join(sources[:3])  # Limit sources shown
                if len(sources) > 3:
                    source_str += f" +{len(sources) - 3} more"
                meta_parts.append(f"📎 {source_str}")

            entities = story.get('entities', [])
            if entities:
                entity_str = ', '.join(entities[:5])
                meta_parts.append(f"🏷️ {entity_str}")

            published = story.get('published')
            if published:
                meta_parts.append(f"🕐 {published}")

            if meta_parts:
                lines.append(' | '.join(meta_parts))

            lines.append("")

        return '\n'.join(lines)


class HTMLRenderer:
    """Render briefing as HTML for email or web."""

    def render(self, result: BriefingResult) -> str:
        meta = result.metadata
        date_str = datetime.now().strftime('%A, %B %d, %Y')

        sections_html = '\n'.join(self._render_section_html(s) for s in result.sections)

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Morning Briefing - {date_str}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 680px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        .header {{
            border-bottom: 3px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
            color: #1e40af;
        }}
        .metadata {{
            color: #6b7280;
            font-size: 14px;
        }}
        .section {{
            margin: 30px 0;
        }}
        .section h2 {{
            color: #1e40af;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 8px;
        }}
        .story {{
            margin: 20px 0;
            padding: 15px;
            background: #f9fafb;
            border-radius: 8px;
            border-left: 4px solid #d1d5db;
        }}
        .story.must_read {{ border-left-color: #dc2626; }}
        .story.important {{ border-left-color: #f59e0b; }}
        .story h3 {{
            margin: 0 0 10px 0;
            font-size: 16px;
        }}
        .story h3 a {{
            color: #1e40af;
            text-decoration: none;
        }}
        .story h3 a:hover {{
            text-decoration: underline;
        }}
        .tier-badge {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            text-transform: uppercase;
            margin-left: 8px;
        }}
        .tier-badge.must_read {{ background: #fee2e2; color: #dc2626; }}
        .tier-badge.important {{ background: #fef3c7; color: #f59e0b; }}
        .tier-badge.contextual {{ background: #d1fae5; color: #059669; }}
        .urgency {{ color: #dc2626; font-weight: bold; }}
        .summary {{
            margin: 10px 0;
            color: #4b5563;
        }}
        .meta {{
            font-size: 12px;
            color: #6b7280;
            margin-top: 10px;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📰 Morning Briefing</h1>
        <div class="metadata">
            {date_str} • {meta.total_stories} stories from {meta.sources_used} sources
            • ~{meta.reading_time_minutes} min read
        </div>
    </div>

    {sections_html}

    <div class="footer">
        Generated by High-Signal News • {meta.generated_at[:19]}
    </div>
</body>
</html>"""

    def _render_section_html(self, section: BriefingSection) -> str:
        stories_html = '\n'.join(
            self._render_story_html(s) for s in section.stories
        )

        return f"""
    <div class="section">
        <h2>{section.emoji} {section.name}</h2>
        {stories_html}
    </div>"""

    def _render_story_html(self, story: dict) -> str:
        tier = story.get('tier', 'contextual')
        urgency = story.get('urgency', 'normal')

        urgency_html = ''
        if urgency == 'breaking':
            urgency_html = '<span class="urgency">BREAKING</span> '
        elif urgency == 'urgent':
            urgency_html = '<span class="urgency">URGENT</span> '

        title = story.get('title', 'Untitled')
        url = story.get('url')
        if url:
            title_html = f'<a href="{url}">{title}</a>'
        else:
            title_html = title

        summary = story.get('summary', '')

        # Meta line
        meta_parts = []
        sources = story.get('sources', [])
        if sources:
            meta_parts.append(f"📎 {', '.join(sources[:3])}")
        entities = story.get('entities', [])
        if entities:
            meta_parts.append(f"🏷️ {', '.join(entities[:5])}")

        meta_html = ' | '.join(meta_parts) if meta_parts else ''

        return f"""
        <div class="story {tier}">
            <h3>{urgency_html}{title_html}<span class="tier-badge {tier}">{tier.replace('_', ' ')}</span></h3>
            <div class="summary">{summary}</div>
            <div class="meta">{meta_html}</div>
        </div>"""


class TextRenderer:
    """Render briefing as plain text for terminal or SMS."""

    def render(self, result: BriefingResult) -> str:
        lines = []

        date_str = datetime.now().strftime('%A, %B %d, %Y')
        lines.append(f"MORNING BRIEFING - {date_str}")
        lines.append("=" * 50)
        lines.append("")

        meta = result.metadata
        lines.append(f"{meta.total_stories} stories from {meta.sources_used} sources")
        lines.append(f"Must read: {meta.must_read_count} | Important: {meta.important_count}")
        lines.append(f"Est. reading time: {meta.reading_time_minutes} min")
        lines.append("")

        for section in result.sections:
            lines.append(self._render_section_text(section))

        lines.append("=" * 50)
        lines.append("Generated by High-Signal News")

        return '\n'.join(lines)

    def _render_section_text(self, section: BriefingSection) -> str:
        lines = []
        lines.append(f"{section.name.upper()}")
        lines.append("-" * 40)
        lines.append("")

        for i, story in enumerate(section.stories, 1):
            tier = story.get('tier', 'contextual')
            urgency = story.get('urgency', 'normal')

            tier_marker = {'must_read': '[MUST]', 'important': '[IMP]', 'contextual': '[CTX]'}.get(tier, '[---]')
            urgency_marker = '[BREAKING] ' if urgency == 'breaking' else '[URGENT] ' if urgency == 'urgent' else ''

            lines.append(f"{i}. {tier_marker} {urgency_marker}{story.get('title', 'Untitled')}")

            summary = story.get('summary', '')
            if summary:
                # Wrap summary at 60 chars
                wrapped = self._wrap_text(summary, 60)
                lines.append(f"   {wrapped}")

            url = story.get('url')
            if url:
                lines.append(f"   Link: {url}")

            lines.append("")

        return '\n'.join(lines)

    def _wrap_text(self, text: str, width: int) -> str:
        """Simple text wrapper."""
        words = text.split()
        lines = []
        current = []
        current_len = 0

        for word in words:
            if current_len + len(word) + 1 > width:
                lines.append(' '.join(current))
                current = [word]
                current_len = len(word)
            else:
                current.append(word)
                current_len += len(word) + 1

        if current:
            lines.append(' '.join(current))

        return '\n   '.join(lines)


# Convenience functions
def render_markdown(result: BriefingResult) -> str:
    """Quick markdown render."""
    return MarkdownRenderer().render(result)


def render_html(result: BriefingResult) -> str:
    """Quick HTML render."""
    return HTMLRenderer().render(result)


def render_text(result: BriefingResult) -> str:
    """Quick text render."""
    return TextRenderer().render(result)
