#!/usr/bin/env python3
"""
Tests for the briefing renderer module.
"""

import sys
from pathlib import Path

import pytest

# Add scripts to path
sys.path.insert(0, str(Path(__file__).parent.parent / 'scripts'))

from briefing.generator import BriefingMetadata, BriefingResult, BriefingSection
from briefing.renderer import (
    MarkdownRenderer,
    HTMLRenderer,
    TextRenderer,
    render_markdown,
    render_html,
    render_text,
)


@pytest.fixture
def sample_result():
    """Create a sample briefing result for testing."""
    meta = BriefingMetadata(
        generated_at="2024-03-21T10:00:00",
        total_stories=3,
        must_read_count=1,
        important_count=1,
        contextual_count=1,
        sources_used=2,
        reading_time_minutes=5
    )
    
    stories = [
        {
            'title': 'Breaking AI News',
            'summary': 'OpenAI releases new model with significant improvements.',
            'sources': ['TechCrunch', 'The Verge'],
            'tier': 'must_read',
            'entities': ['OpenAI', 'GPT'],
            'urgency': 'breaking',
            'url': 'https://example.com/ai',
            'published': '2024-03-21'
        },
        {
            'title': 'Python Update',
            'summary': 'New security patch released.',
            'sources': ['Python Blog'],
            'tier': 'important',
            'entities': ['Python'],
            'urgency': 'normal',
        },
        {
            'title': 'Market News',
            'summary': 'VC funding trends.',
            'sources': ['Bloomberg'],
            'tier': 'contextual',
            'entities': [],
            'urgency': 'normal',
        }
    ]
    
    sections = [
        BriefingSection(name='AI', emoji='🤖', stories=stories[:1]),
        BriefingSection(name='Software', emoji='💻', stories=stories[1:2]),
        BriefingSection(name='Investment', emoji='💰', stories=stories[2:]),
    ]
    
    return BriefingResult(metadata=meta, sections=sections)


class TestMarkdownRenderer:
    """Test MarkdownRenderer."""
    
    @pytest.fixture
    def renderer(self):
        return MarkdownRenderer()
    
    def test_render_header(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '# 📰 Morning Briefing' in output
        assert '3 stories' in output
        assert '2 sources' in output
    
    def test_render_sections(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '## 🤖 AI' in output
        assert '## 💻 Software' in output
        assert '## 💰 Investment' in output
    
    def test_render_tier_emojis(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '🔴' in output  # must_read
        assert '🟡' in output  # important
        assert '🟢' in output  # contextual
    
    def test_render_urgency_markers(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '**BREAKING**' in output
    
    def test_render_links(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '[Breaking AI News](https://example.com/ai)' in output
    
    def test_render_metadata_line(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '📎' in output  # Sources indicator
        assert '🏷️' in output  # Entities indicator
    
    def test_render_empty_section(self, renderer):
        result = BriefingResult(
            metadata=BriefingMetadata(
                generated_at="2024-01-01",
                total_stories=0,
                must_read_count=0,
                important_count=0,
                contextual_count=0,
                sources_used=0,
                reading_time_minutes=0
            ),
            sections=[BriefingSection(name='Empty', emoji='📭', stories=[])]
        )
        output = renderer.render(result)
        assert '*No stories in this section.*' in output
    
    def test_render_footer(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '*Generated by High-Signal News*' in output


class TestHTMLRenderer:
    """Test HTMLRenderer."""
    
    @pytest.fixture
    def renderer(self):
        return HTMLRenderer()
    
    def test_render_html_structure(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '<!DOCTYPE html>' in output
        assert '<html>' in output
        assert '</html>' in output
    
    def test_render_styles(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '<style>' in output
        assert 'story must_read' in output
        assert 'story important' in output
    
    def test_render_sections(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '<h2>🤖 AI</h2>' in output
        assert '<h2>💻 Software</h2>' in output
    
    def test_render_tier_badges(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert 'tier-badge must_read' in output
        assert 'tier-badge important' in output
    
    def test_render_urgency(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert 'class="urgency"' in output
        assert 'BREAKING' in output
    
    def test_render_links(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert 'href="https://example.com/ai"' in output


class TestTextRenderer:
    """Test TextRenderer."""
    
    @pytest.fixture
    def renderer(self):
        return TextRenderer()
    
    def test_render_header(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert 'MORNING BRIEFING' in output
        assert '=' * 40 in output or '=' * 50 in output
    
    def test_render_sections(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert 'AI' in output
        assert 'SOFTWARE' in output
    
    def test_render_tier_markers(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '[MUST]' in output
        assert '[IMP]' in output
        assert '[CTX]' in output
    
    def test_render_urgency_markers(self, renderer, sample_result):
        output = renderer.render(sample_result)
        assert '[BREAKING]' in output
    
    def test_render_wraps_text(self, renderer, sample_result):
        output = renderer.render(sample_result)
        # Should not have extremely long lines
        lines = output.split('\n')
        for line in lines:
            assert len(line) <= 80  # Reasonable wrap width
    
    def test_wrap_text_method(self, renderer):
        long_text = "This is a very long sentence that should be wrapped at the appropriate width."
        wrapped = renderer._wrap_text(long_text, 30)
        lines = wrapped.split('\n')
        for line in lines:
            # Account for the "   " prefix added by _wrap_text
            assert len(line) <= 33  # 30 + 3 space prefix


class TestConvenienceFunctions:
    """Test the convenience render functions."""
    
    @pytest.fixture
    def simple_result(self):
        return BriefingResult(
            metadata=BriefingMetadata(
                generated_at="2024-01-01",
                total_stories=1,
                must_read_count=1,
                important_count=0,
                contextual_count=0,
                sources_used=1,
                reading_time_minutes=1
            ),
            sections=[
                BriefingSection(name='AI', emoji='🤖', stories=[{
                    'title': 'Test',
                    'summary': 'Summary',
                    'sources': ['Source'],
                    'tier': 'must_read',
                    'entities': [],
                    'urgency': 'normal',
                }])
            ]
        )
    
    def test_render_markdown(self, simple_result):
        output = render_markdown(simple_result)
        assert '# 📰 Morning Briefing' in output
    
    def test_render_html(self, simple_result):
        output = render_html(simple_result)
        assert '<!DOCTYPE html>' in output
    
    def test_render_text(self, simple_result):
        output = render_text(simple_result)
        assert 'MORNING BRIEFING' in output


class TestRendererEdgeCases:
    """Test edge cases for renderers."""
    
    @pytest.fixture
    def empty_result(self):
        return BriefingResult(
            metadata=BriefingMetadata(
                generated_at="2024-01-01",
                total_stories=0,
                must_read_count=0,
                important_count=0,
                contextual_count=0,
                sources_used=0,
                reading_time_minutes=0
            ),
            sections=[]
        )
    
    def test_markdown_empty_sections(self, empty_result):
        renderer = MarkdownRenderer()
        output = renderer.render(empty_result)
        assert '0 stories' in output
        assert '0 sources' in output
    
    def test_html_empty_sections(self, empty_result):
        renderer = HTMLRenderer()
        output = renderer.render(empty_result)
        assert '<body>' in output
        assert '</body>' in output
    
    def test_text_empty_sections(self, empty_result):
        renderer = TextRenderer()
        output = renderer.render(empty_result)
        assert '0 stories' in output
    
    def test_story_without_url(self):
        """Test rendering a story without a URL."""
        result = BriefingResult(
            metadata=BriefingMetadata(
                generated_at="2024-01-01",
                total_stories=1,
                must_read_count=0,
                important_count=1,
                contextual_count=0,
                sources_used=1,
                reading_time_minutes=1
            ),
            sections=[
                BriefingSection(name='Test', emoji='🧪', stories=[{
                    'title': 'No URL Story',
                    'summary': 'This story has no URL.',
                    'sources': ['Source'],
                    'tier': 'important',
                    'entities': [],
                    'urgency': 'normal',
                }])
            ]
        )
        
        md = render_markdown(result)
        assert 'No URL Story' in md
        assert '](http' not in md  # Should not create empty link
        
        html = render_html(result)
        assert 'No URL Story' in html
        assert 'href=' not in html  # Should not have link


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
